# Generated by Django 3.2.9 on 2023-03-20 07:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutlayType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o_type', models.CharField(max_length=10, verbose_name='Xarajat turi')),
            ],
            options={
                'verbose_name_plural': 'Xarajatlar Turi',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='cost_price',
        ),
        migrations.CreateModel(
            name='Outlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=1, max_digits=11)),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 3, 20, 12, 33, 8, 799225))),
                ('description', models.TextField(verbose_name='Izoh')),
                ('outlay_type', models.ForeignKey(default='Boshqalar', on_delete=django.db.models.deletion.SET_DEFAULT, to='products.outlaytype', verbose_name='Xarajat turi')),
            ],
            options={
                'verbose_name_plural': 'Xarajatlar',
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_price', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Sotib olingan mnarx')),
                ('kilo_per_metr', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='Kilosiga metri')),
                ('price_per_metr', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name="Metriga yo'l kira")),
                ('cost_price', models.DecimalField(decimal_places=3, max_digits=7, verbose_name='Tannarx')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
